# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: All Papers
    parent: Research
    url: /#papers
    weight: 20
  - name: Research Themes
    parent: Research
    url: research/
    weight: 30
  - name: Projects
    parent: Research
    url: projects/
    weight: 40
  - name: Talks
    url: /#talks
    weight: 50
  - name: Service
    url: #collaboration
    weight: 60
  - name: Experience
    url: experience/
    weight: 70
  - name: Collaboration
    url: collaboration/
    weight: 80
  - name: Teaching
    url: teaching/
    weight: 90
  - name: Trading
    url: teaching/
    weight: 100
  - name: Blogs
    url: post/
    weight: 110
